spring.application.name=atividade-extensionista

spring.datasource.username={$DB_USERNAME}
spring.datasource.password={$DB_PASSWORD}
spring.datasource.url={$DB_URL}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true